name: cbom
on:
 
  branch_protection_rule:
  push:
    branches: [ "18.0.1_tavoss" ]
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  cbom-scan:
    runs-on: ubuntu-latest
    name: CBOM generation
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: "18.0.1_tavoss" # Ensure the correct branch is checked out

      - name: Create CBOM
        uses: PQCA/cbomkit-action@v1.1.0
        id: cbom
        continue-on-error: true

      - name: Create and publish CBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: "CBOM"
          path: cbom.json
